export const messages = {
  en: {
    home: "Home",
    about: "About Us",
    disasters: "Disasters",
    contact: "Contact Us",
    forAuthority: "For Authority",
    forAuthorityContent: "Stay informed with real-time hazard reports from citizens. With verified alerts and faster communication, authorities can coordinate responses effectively and ensure the safety of coastal communities.",
    login: "Login",
    report: "Report",
    join: "Don't have an account?",
    joinAsAuthority: "Join as Authority",
    forCitizens: "For Citizens",
    forCitizensContent: "Your eyes on the coast can make a real difference. By reporting hazards instantly and sharing vital information, you help protect lives and support safer shores for everyone.",
    signUp: "Sign Up",
    dashboard: "Disaster Dashboard",
    aboutUs: "About Us",
    aboutSamudram: "About Samudram",
    aboutPara: "Harnessing the power of citizens, AI, and ocean intelligence to build safer coastlines.",
    aboutDesc: "Samudram is an ocean hazard monitoring platform built to connect citizens and authorities in real time...",
    ourMission: "Our Mission & Our Vision",
    contactUs: "Contact Us",
    sendMessage: "Send a message",
    submit: "Submit",
    getInTouch: "Get in Touch",
    location: "Location",
    email: "Email",
    phone: "Phone",
    footer: "© 2025 Samudram. All rights reserved.",
    verifyAuthority: "Verify as an authority",
    authorityId: "Authority ID",
    enterOtp: "Enter Otp",
    submitting: "Submitting...",
    submitBtn: "Submit"
  },
  hi: {
    home: "होम",
    about: "हमारे बारे में",
    disasters: "आपदाएँ",
    contact: "संपर्क करें",
    forAuthority: "प्राधिकरण के लिए",
    forAuthorityContent: "नागरिकों से वास्तविक समय खतरों की रिपोर्ट से सूचित रहें...",
    login: "लॉगिन",
    report: "रिपोर्ट",
    join: "क्या आपका खाता नहीं है?",
    joinAsAuthority: "प्राधिकरण के रूप में शामिल हों",
    forCitizens: "नागरिकों के लिए",
    forCitizensContent: "तट पर आपकी नज़रें बड़ा फर्क ला सकती हैं...",
    signUp: "साइन अप करें",
    dashboard: "आपदा डैशबोर्ड",
    aboutUs: "हमारे बारे में",
    aboutSamudram: "समुद्रम के बारे में",
    aboutPara: "नागरिकों, AI और महासागर बुद्धिमत्ता की शक्ति का उपयोग...",
    aboutDesc: "समुद्रम एक महासागर खतरा निगरानी मंच है...",
    ourMission: "हमारा मिशन और हमारा विज़न",
    contactUs: "संपर्क करें",
    sendMessage: "संदेश भेजें",
    submit: "सबमिट करें",
    getInTouch: "संपर्क में रहें",
    location: "स्थान",
    email: "ईमेल",
    phone: "फोन",
    footer: "© 2025 समुद्रम. सर्वाधिकार सुरक्षित.",
    verifyAuthority: "प्राधिकरण के रूप में सत्यापित करें",
    authorityId: "प्राधिकरण आईडी",
    enterOtp: "ओटीपी दर्ज करें",
    submitting: "सबमिट हो रहा है...",
    submitBtn: "सबमिट करें"
  }
};
